name = "awlvertexglowmarker"
main = "src/index.js"
compatibility_date = "2025-01-01"

[vars]
OAUTH_REDIRECT_HOST = "awlvertexglowmarker.chinafang1234.workers.dev"
OAUTH_ORIGIN = "https://popcornedward.github.io"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-astro-avgm"
